### ISSUE TITLE
SASL Jass config

### ISSUE THREAD

**Issue by paraut** [jenkinsci/remoting-kafka-plugin#46]
I am not sure if you can use Jass config to connect to Kafka using Jenkins UI. I have provided Kafka server name with port and Kafka credentials with username and password. But it doesn't connect and there is just the mentioned of ERROR but that link doesn't work so I can't see what the error is. 

Is it possible for you to provide example configuration for JASS config on Jenkins UI( which means just the username and password)

**Comment by pvtuan10** [comment]
Hi @paraut, have you taken a look at this config file yet? https://github.com/jenkinsci/remoting-kafka-plugin/blob/master/demo/jenkins.yaml#L25-L61, this is what I have done for my JASS config

**Comment by pvtuan10** [comment]
Let me know if you do not understand or have any queries

**Comment by oleg-nenashev** [comment]
Matbe it makes sense to disable GitHub issues in this repo. WDYT @pvtuan10 ?

**Comment by pvtuan10** [comment]
then how users can report issues if they dont know about JIRA?

**Comment by oleg-nenashev** [comment]
All Jenkins users know about JIRA.
But you could reference https://wiki.jenkins.io/display/JENKINS/How+to+report+an+issue from README

Anyway, it's up to you

**Comment by pvtuan10** [comment]
oh, if this is a convention by our community then I will disable this section

**Comment by pvtuan10** [comment]
Close due to inactivity.
